use Restaurant
db.restaurant.find({})
db.restaurant.find({}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id:0})
db.restaurant.find({},{restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0})
db.restaurant.find({},{restaurant_id: 1, name: 1, borough: 1, "address.zipcode": 1, _id: 0})
db.restaurant.find({borough: "Bronx"})
db.restaurant.find({borough: "Bronx"}).limit(5)
db.restaurant.find({borough: "Bronx"}).skip(5).limit(5)
db.restaurant.find({"grades.score": {$gt : 90}})
db.restaurant.find({"grades.score": {$gt : 80, $lt : 100}})
db.restaurant.find({"address.coord.1": {$lt :  -95.754168}})
db.restaurant.find({$and: [{cuisine : {$ne: "American "}},{"grades.score": {$gt: 70}},{"address.coord.0": {$lt : -65.754168}}]})
db.restaurant.find({cuisine : {$ne: "American "},"grades.score":{$gt: 70},"address.coord.0": {$lt : -65.754168}})
db.restaurant.find({cuisine : {$ne: 'American '},"grades.grade":'A',borough:{$ne:'Brooklyn'}}).sort({cuisine: -1})
db.restaurant.find({name:{ $regex: '^Wil'}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurant.find({name : {$regex: 'ces$'}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurant.find({name : {$regex: 'Reg'}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurant.find({borough:'Bronx',cuisine:{$in:['American ','Chinese']}})
db.restaurant.find({borough: {$in: ['Staten Island','Queens','Bronx','Brooklyn']}})
db.restaurant.find({borough: {$nin: ['Staten Island','Queens','Bronx','Brooklyn']}})
db.restaurant.find({"grades.score":{$lt: 11}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1,_id:0})
db.restaurant.find({$or:[{cuisine: "Seafood"},{name :{$regex: '^Wil'}}]},{restaurant_id:1,name:1,_id:0,borough:1,cuisine:1})
db.restaurant.find({grades:{$elemMatch: {grade:"A",score:11,date:ISODate("2014-08-11T00:00:00Z")}}},{restaurant_id:1,name:1,_id:0,grades:1})
db.restaurant.find({"grades.1.grade":"A","grades.1.score":9,"grades.1.date":ISODate("2014-08-11T00:00:00Z")},{restaurant_id:1,name:1,_id:0,grades:1})
db.restaurant.find({"address.coord.1":{$gt:42,$lte:52}},{restaurant_id:1,name:1,_id:0,address:1})
db.restaurant.find({}).sort({name:1})
db.restaurant.find({}).sort({name:-1})
db.restaurant.find({}).sort({cuisine:1,borough:-1})
db.restaurant.find({"address.street":{$exists: false}})
db.restaurant.find({"address.coord.0":{$type:"double"}})
db.restaurant.find({"grades.score":{$mod:[7,0]}},{restaurant_id:1,name:1,_id:0,"grades":1})
db.restaurant.find({name:{$regex: 'mon'}},{name:1,_id:0,borough:1,"address.coord":1,cuisine:1})
db.restaurant.find({name:{$regex: '^Mad'}},{name:1,_id:0,borough:1,"address.coord":1,cuisine:1})
